[package]
name = "rust-echo-server"
version = "0.1.0"
authors = ["minami14 <minami-git@minami-vr.sakura.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
